### ISSUE TITLE
#1 [프로젝트_내 프로젝트] : 내 프로젝트 페이지 폴더 배열 이슈

### ISSUE THREAD

**Issue by kimgorok** [Talk-Kit/talk-kit-frontend#1]
![image](https://github.com/Talk-Kit/talk-kit-frontend/assets/128457944/464094b9-2921-4902-b988-6982cae1d57b)

첨부한 사진은 현재 justify-start와 flex-wrap을 적용하여, 폴더의 수가 한 줄이 넘어갈 경우 다음 줄의 왼쪽에서부터 정렬되도록 설정했습니다.

그러나 다음 줄로 넘어가면서 약간의 여백이 생깁니다.

justify-center를 할 경우에는 전체적으로 중앙 정렬이 되나, 다음 줄로 넘어갔을 때에도 중앙부터 시작합니다.

mx-auto도 적용이 안되는 상태입니다.

**Comment by seorang42** [comment]
일단 현재 display를 flex 속성으로 하여 배열을 설정해두신 것으로 확인이 되는데, grid를 사용하여 한 행에 들어가는 개수를 조절해주는 것이 더 좋아보입니다.

1. tailwind의 className에 grid grid-cols-5를 통해 한 줄에 5개의 폴더가 출력되게 생성하고, gap을 사용하여 폴더간의 간격을 맞춘다.
2. 피그마를 기준으로 폴더 컴포넌트의 크기가 화면의 크기에 따라 달라지지 않기 때문에, 부모 엘리먼트의 className에 w-fit을 주어 안의 폴더만큼의 너비로 감싼다. 
3. 해당 부모 컴포넌트의 상위 컴포넌트에 중앙 정렬을 걸어 전체 폴더 컴포넌트를 전체적으로 중앙정렬한다(폴더 정렬 구조에 영향을 주지 않게 하기 위함).

예시 코드 : 
```
<div className="w-full flex justify-center">
     <div className="grid grid-cols-5 gap-8 w-fit">
          {[1, 1, 1, 1, 1, 1].map((el) => <div className="w-40 h-40 bg-gray-4" />)}
     </div>
</div>
```

<img width="1261" alt="스크린샷 2024-07-09 오후 8 11 09" src="https://github.com/Talk-Kit/talk-kit-frontend/assets/123955813/ffbadbe7-a268-4db6-b100-9563eb56aa60">
